Hotel/Hotel/Models/FeedBack.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Hotel.Models
{
    public class FeedBack
    {
        public int ID { get; set; }
        [DisplayName("Hotel Name")]
        public string Subject { get; set; }
        [DisplayName("Details about the Feedback of Hotel")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        // Hotel ID as a foreign key
        [HiddenInput(DisplayValue = false)]
        public string HotelID { get; set; }
    }
}

Hotel/Hotel/Models/General.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hotel.Models
{
    public class General
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your email address")]
        [RegularExpression(".+\\@.+\\..+",
        ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }

        
        [Required(ErrorMessage = "Please enter your password")]
        [RegularExpression("([a-z]|[A-Z]|[0-9]|[\\W]){4}[a-zA-Z0-9\\W]{3,11}", ErrorMessage = "Invalid password format")]
        [MinLength(8, ErrorMessage = "Minimum length of 8 characters is required")]
        public string Password { get; set; }

        [NotMapped] // Does not effect with database
        [Required(ErrorMessage = "Confirm Password is required")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Please enter type")]
        public string UserType { get; set; }

    }
}

Hotel/Hotel/Controllers/FeedBacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel;

namespace Hotel.Controllers
{
    public class FeedBacksController : Controller
    {
        private HotelEntities db = new HotelEntities();

        // GET: FeedBacks
        public ActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var feedBack = from s in db.FeedBacks
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                feedBack = feedBack.Where(s => s.HotelName.Contains(searchString)
                                       || s.HotelName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    feedBack = feedBack.OrderByDescending(s => s.HotelName);
                    break;

                default:
                    feedBack = feedBack.OrderBy(s => s.HotelName);
                    break;
            }
            return View(db.FeedBacks.ToList());
        }

        public ActionResult Feedback()
        {
            return View();
        }

        // GET: FeedBacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // GET: FeedBacks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FeedBacks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,HotelName,Feedback1,Id")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                db.FeedBacks.Add(feedBack);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(feedBack);
        }

        // GET: FeedBacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // POST: FeedBacks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,HotelName,Feedback1,Id")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedBack).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedBack);
        }

        // GET: FeedBacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // POST: FeedBacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FeedBack feedBack = db.FeedBacks.Find(id);
            db.FeedBacks.Remove(feedBack);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel/Hotel/Controllers/GeneralsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Hotel;
using Hotel.Models;

namespace Hotel.Controllers
{
    
    public class GeneralsController : Controller
    {
        private HotelEntities db = new HotelEntities();

        // GET: Generals
        public ActionResult Index()
        {
            return View(db.Generals.ToList());
        }

        public ActionResult SignUp()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult favourites()
        {
            return View();
        }

        public ActionResult user()
        {
            return View();
        }

        public ActionResult map()
        {
            return View();
        }
        //feedback
        public ActionResult feedback()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult feedback([Bind(Include = "UserName,HotelName,comment,Id")] FeedBack obj)
        {

            try
            {

                obj.UserName = HotelStatic.username;


                if (ModelState.IsValid)
                {
                    db.FeedBacks.Add(obj);
                    db.SaveChanges();

                    return RedirectToAction("Dashboard");
                }
            }

            catch (DataException)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");

            }
            return View(obj);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(General entity)
        {
            using (HotelEntities db = new HotelEntities())
            {
                //fetche the data of user on the basis of inserted email
                General user = db.Generals.FirstOrDefault(u => u.Email == (entity.Email));
                //if entered email is not bound to any user then object will be null
                if (user == null)
                {
                    TempData["ErrorMSG"] = "object not found";
                    return View(entity);

                }
                //if we are here then it mean we sucsessfuly retrived the data
                //now we compare password
                int a = entity.Password.Count();
                if (user.Password.Substring(0, a) != entity.Password)
                {
                    TempData["ErrorMSG"] = "Password not matched";
                    return View(entity);

                }

                if (user != null)
                {
                    

                    if (user.Password.Substring(0, a) == entity.Password)
                    {

                       // var Users = new UserStatic();
                        if (user.Type.Substring(0, 5) == "Admin")
                            return RedirectToAction("AdminDash", "HotelDatas");
                        if (user.Type.Substring(0, 12) == "HotelManager")
                        {

                            // first add hotel by hotel manger then hotelmanger will able to see dashboard
                            return RedirectToAction("AddHotel1", "HotelDatas");
                        }
                        if (user.Type.Substring(0, 4) == "User")
                        {
                            HotelStatic.username = user.Name;
                            HotelStatic.Id = user.ID;
                            return RedirectToAction("Dashboard");
                        }
                    }
                    return View();
                }
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult user([Bind(Include = "FirstName,LastName,Adress,City,Country,PostalCode,About,UserID,ID")] UserData obj)
        {

            try
            {

                obj.ID = HotelStatic.Id;

                UserData user = db.UserDatas.FirstOrDefault(u => u.ID == (obj.ID));
                //user will not be null if current entered id is present in database
                if (user != null)
                    ModelState.AddModelError("ID", "You already entered your data");

                if (ModelState.IsValid)
                {
                    db.UserDatas.Add(obj);
                    db.SaveChanges();

                    return RedirectToAction("Dashboard");
                }
            }

            catch (DataException)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");

            }
            return View(obj);


        }



        // GET: Generals/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            General general = db.Generals.Find(id);
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // GET: Generals/Create
        public ActionResult Dashboard()
        {
            return View();
        }

        

        

        // POST: Generals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp([Bind(Include = "ID,Name,Email,Password,ConfirmPassword,Type")] General general)
        {
            try
            {
                //check if email already exist

                General user = db.Generals.FirstOrDefault(u => u.Email == (general.Email));
                //user will not be null if current entered email is presenyt in database
                if (user != null)
                    ModelState.AddModelError("Email", "This Email was already taken");
                //sucessfull signup procedure
                if (ModelState.IsValid && user == null)
                {
                    db.Generals.Add(general);
                    db.SaveChanges();
                    
                    //after saving data in database
                    //we check for type of user and direct it to respective database
                    if (general.Type == "Admin")
                        return RedirectToAction("AdminDash", "HotelDatas");
                    if (general.Type == "HotelManager")
                    {
                        // first add hotel by hotel manger then hotelmanger will able to see dashboard
                        return RedirectToAction("AddHotel1", "HotelDatas");
                    }
                    if (general.Type == "User")
                    {
                        HotelStatic.username = general.Name;
                        HotelStatic.Id = general.ID;
                        return RedirectToAction("Dashboard");
                    }
                }
            }

            catch (DataException)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(general);
        }

        // GET: Generals/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            General general = db.Generals.Find(id);
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // POST: Generals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Email,Password,ConfirmPassword,Type")] General general)
        {
            if (ModelState.IsValid)
            {
                db.Entry(general).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(general);
        }

        // GET: Generals/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            General general = db.Generals.Find(id);
            if (general == null)
            {
                return HttpNotFound();
            }
            return View(general);
        }

        // POST: Generals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            General general = db.Generals.Find(id);
            db.Generals.Remove(general);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        
        //Logout//
        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

Hotel/Hotel/Views/Generals/Delete.cshtml
@model Hotel.General

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>General</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel/Hotel/Views/Generals/Login.cshtml
@model Hotel.General

@{
    ViewBag.Title = "Login";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/assets/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/assets/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/utillogin.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/mainlogin.css">
    <!--===============================================================================================-->
</head>
<body>
    @using (Html.BeginForm("Login", "Generals", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div>
            <div class="container-login100" style="background-image: url('http://localhost:50617/assets/images/p3.jpg');">
                <div class="wrap-login100">
                    <form class="login100-form validate-form">
                        <span class="login100-form-logo">
                            <i class="zmdi zmdi-landscape"></i>
                        </span>

                        <span class="login100-form-title p-b-34 p-t-27">
                            Log in
                        </span>

                        <div class="wrap-input100 validate-input" data-validate="Enter username">

                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "input100" })
                            @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "input100" }, style = "background-color: #99b9ff; color: white" })
                            <span class="focus-input100" data-placeholder="&#xf207;"></span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate="Enter password">

                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "input100" })
                            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "input100" }, style = "background-color: #99b9ff; color: white" })
                            <span class="focus-input100" data-placeholder="&#xf191;"></span>
                        </div>

                        <div class="contact100-form-checkbox">
                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                            <label class="label-checkbox100" for="ckb1">
                                Remember me
                            </label>
                        </div>

                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn">
                                Login
                            </button>
                        </div>
                        
                        <div class="text-center p-t-136">
                            <a href="@Url.Action("SignUp", "Generals")">
                                <i class="fa fa-long-arrow-right m-l-5"  aria-hidden="true"></i>
                                <p>Create Your account</p>
                            </a>
                            
                        </div>

                        <div class="text-center p-t-90">
                            <a class="txt1" href="#">
                                Forgot Password?
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div id="dropDownSelect1"></div>
    }

    <!--===============================================================================================-->
    <script src="~/assets/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/vendor/bootstrap/js/popper.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/assets/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/assets/js/mainlogin.js"></script>

</body>
</html>

Hotel/Hotel/Views/Generals/favourites.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Favourites
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="assets/css/now-ui-dashboard.css?v=1.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="assets/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="orange">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
       
        <a class="simple-text logo-normal">
          TravOre
        </a>
      </div>
      <div class="sidebar-wrapper">
          <ul class="nav">
              <li class="active ">
                  <a href="@Url.Action("Dashboard", "Generals")">
                      <i class="now-ui-icons design_app"></i>
                      <p>Dashboard</p>
                  </a>
              </li>

              <li>
                  <a href="@Url.Action("map", "Generals")">
                      <i class="now-ui-icons location_map-big"></i>
                      <p>Maps</p>
                  </a>
              </li>
              <li>
                  <a href="@Url.Action("feedback", "Generals")">
                      <i class="now-ui-icons ui-1_bell-53"></i>
                      <p>Feedback</p>
                  </a>
              </li>
              <li>
                  <a href="@Url.Action("user", "Generals")">
                      <i class="now-ui-icons users_single-02"></i>
                      <p>User Profile</p>
                  </a>
              </li>
              <li>
                  <a href="@Url.Action("favourites", "Generals")">
                      <i class="now-ui-icons design_bullet-list-67"></i>
                      <p>Favourites</p>
                  </a>
              </li>

              <li>
                  <a href="@Url.Action("Index", "Home")">
                      <i class="fas fa-sign-out-alt"></i>
                      <p>Log Out</p>
                  </a>
              </li>

          </ul>
      </div>
  </div>

         <!-- Navbar -->
      <nav class="navbar navbar-expand-lg fixed-top navbar-transparent  bg-primary  navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">TravOre</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          
        </div>
      </nav>
      <!-- End Navbar -->


      <div class="main-panel">
     
      <div class="panel-header panel-header-sm">
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-8">
            <div class="card">
              <div class="card-header">
                <h5 class="title">Favourites</h5>
              </div>
              <div class="card-body">
                <form>
                
                    
                    
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Write favourite</label>
                        <input type="text" class="form-control">
                      </div>
                    </div>
                  </div>
                  

                  <button class="button search_button1">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      



      
      </div>
      <div class="content" style="margin-top:-300px">
        <div class="row">
          <div class="col-md-8">
            <div class="card">
              <div class="card-header">
                <h5 class="title">Favourites</h5>
              </div>
              <div class="card-body">
              <textarea> </textarea>
              </div>
            </div>
          </div>
        </div>
      
    </div>
    
          

  <!--   Core JS Files   -->
  <script src="assets/js/core/jquery.min.js"></script>
  <script src="assets/js/core/popper.min.js"></script>
  <script src="assets/js/core/bootstrap.min.js"></script>
  <script src="assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="assets/js/now-ui-dashboard.min.js?v=1.1.0" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="assets/demo/demo.js"></script>
</body>

</html>